function [cathode,anode,electrolyte,reaction,data] = initParams(paramFolder)
csvFiles = dir(fullfile(paramFolder,"*cellParams.csv"));
if isempty(csvFiles)
    error('initParams:MissingCSV', 'No CSV file found in parameter folder: %s', paramFolder);
end
if numel(csvFiles) > 1
    warning('initParams:MultipleCSV', 'Multiple CSV files found in %s. Using %s.', paramFolder, csvFiles(1).name);
end
csvFile = fullfile(csvFiles(1).folder, csvFiles(1).name);
data                = readtable(csvFile);
data.Symbol         = string(data.Symbol);
    
%% Cathode Parameters
cathode = struct(...
                        'r_start',          0, ...
                        'R_end',            data.Value(data.Symbol == 'R_p'), ...
                        'L',                data.Value(data.Symbol == 'L_p') ,...
                        'alpha',            data.Value(data.Symbol == 'alpha_p'),...
                        'a_s',              data.Value(data.Symbol == 'a_s_p'),...
                        'D_s',              data.Value(data.Symbol == 'D_s_p'),...
                        'cs_max',           data.Value(data.Symbol == 'c_s_max_p'),...
                        'x1',               data.Value(data.Symbol == 'x1_p'), ...
                        'x0',               data.Value(data.Symbol == 'x0_p'),...
                        'epsilon_s',        data.Value(data.Symbol == 'eps_s_p'), ...
                        'k0',               data.Value(data.Symbol == 'k_p'),... %'i0',2.8 
                        'Q_th',             data.Value(data.Symbol == 'Q_th'),... %'i0',2.8 
                        'A',                data.Value(data.Symbol == 'A_cell')... %'i0',2.8 
                        );
cathode.domain          = [0 cathode.R_end];
cathode.cs_ref          = cathode.cs_max/2;


%% Anode Parameters
anode = struct(...
                        'L',                data.Value(data.Symbol == 'L_n'), ...
                        'alpha',            data.Value(data.Symbol == 'alpha_n'), ...
                        'i0',               data.Value(data.Symbol == "i0_ref_n"), ...
                        'k0',               data.Value(data.Symbol == 'k_n')... %'i0',21
                        );

%% Electrolyte Parameters
electrolyte = struct(...
                        'L_sep',            data.Value(data.Symbol == 'L_s'), ...
                        'c_ref',            data.Value(data.Symbol == 'c_e_ref'), ...
                        'epsilon_pos',      data.Value(data.Symbol == 'eps_e_p'), ...
                        'epsilon_sep',      data.Value(data.Symbol == 'eps_e_s'), ...
                        'D_e_cat',          data.Value(data.Symbol == 'D_e_eff_p'), ...  
                        'D_e_sep',          data.Value(data.Symbol == 'D_e_eff_s'), ...
                        'TDF',              data.Value(data.Symbol == 'TDF'), ...
                        't0_plus',          data.Value(data.Symbol == 't_plus'), ...
                        'sigma_e',          data.Value(data.Symbol == 'kappa_e'), ... 
                        'Brugg',            data.Value(data.Symbol == 'brugg_s')...
                        );
electrolyte.domain      = [0 electrolyte.L_sep (electrolyte.L_sep + cathode.L)];
    
%% OCV Interpolant
cathode.ocp_fun =@(soc) interp_ocp(soc, 'soc2v');

%% Stoichiometry and Charge Transfer
reaction = struct(...
                        'nu',               data.Value(data.Symbol == 'nu'), ...
                        'nu_cation',        data.Value(data.Symbol == 'nu_cation'), ...
                        'nu_anion',         data.Value(data.Symbol == 'nu_anion'), ...
                        's_pos_cation',     data.Value(data.Symbol == 's_p_cation'), ...
                        's_pos_anion',      data.Value(data.Symbol == 's_p_anion'), ...
                        's_neg_cation',     data.Value(data.Symbol == 's_n_cation'), ...
                        's_neg_anion',      data.Value(data.Symbol == 's_n_anion'), ...
                        'n_pos_electron',   data.Value(data.Symbol == 'n_e_p'), ...
                        'n_neg_electron',   data.Value(data.Symbol == 'n_e_n'), ...
                        'z_cation',         data.Value(data.Symbol == 'z_cation'), ...
                        'z_anion',          data.Value(data.Symbol == 'z_anion') ...
                        );
end