function saveSimulationResults(simfolder, C_rate, results, cathode, anode, electrolyte)

            simfolder = fullfile(simfolder, sprintf('Crate_%g', C_rate));

            %%% Output Discretization params %%%
            N_s = electrolyte.fem_p*electrolyte.Nxs+1;
            N_c = electrolyte.fem_p*electrolyte.Nxp+1;
            Geometry_cell.cathode = cathode.Geometry;
            Geometry_cell.cathode.Nr = cathode.N*cathode.fem_p+1;
            Geometry_cell.electrolyte = electrolyte.Geometry;
            Geometry_cell.electrolyte.Ns = N_s;
            Geometry_cell.electrolyte.Np = N_c;
            if ~isfolder(simfolder)
                mkdir(simfolder);
            end
            save(fullfile(simfolder,"Geometry_cell.mat"),"-struct","Geometry_cell")

            % Prepare outputs
            Time                = results.T;
            Voltage             = results.Voltage;
            Voltage_pos         = Voltage - 1.03;
            OCP_pos             = results.OCP_pos;
            delta_Etha          = results.delta_eta;
            Etha_cathode        = results.eta_cathode;
            Etha_anode          = results.eta_anode;
            delta_Phie          = results.delta_phi_e;
            cell_SOC            = results.cell_SOC;
            Capacity            = results.Q;
            Css                 = results.css;
            Cs                  = results.cs_all;
            AvgCs               = results.AvgCs;
            Ce                  = results.ce_all;
            AvgCe               = results.ce_avg;
            theta                 = AvgCs./cathode.cs_max;
            i0_cathode          = results.i0_cathode;
            i0_anode            = results.i0_anode;
            jn_cathode          = results.j_cathode;
            jn_anode            = results.j_anode;
    
            Table = table( ...
                Time, ...
                theta, ...
                cell_SOC, ...
                Capacity, ...
                Voltage, ...
                Voltage_pos, ...
                OCP_pos, ...
                Etha_cathode, ...
                Etha_anode, ...
                delta_Etha, ...
                delta_Phie, ...
                Css, ...
                AvgCs, ...
                Cs, ...
                AvgCe, ...
                Ce, ...
                i0_cathode, ...
                i0_anode, ...
                jn_cathode, ...
                jn_anode ...
                );
            Table.Properties.Description = sprintf('C_rate = %d',C_rate);
            Table_name = sprintf("sim_%.d.csv",C_rate);
            Table_fullpath = fullfile(simfolder,Table_name);
            writetable(Table,Table_fullpath,'Delimiter',',');
end